### ISSUE TITLE
HELP command declaration not found

### ISSUE THREAD

**Issue by danbulant** [Littlemansmg/Discord-Meme-Generator#1]
Hello. I tried translating your code as much as possible, but I didn't locate help command. Is it in code or it is in discord.py?

**Comment by danbulant** [comment]
Oh, found it's in discord.py and can be changed.

**Comment by Littlemansmg** [comment]
Just so you know, this uses some pretty bad practices. A better way to handle commands is in Pydump-async. You can also talk to me directly through the r/discord_bots discord server.
